server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /api/center {
        proxy_pass http://CIS-alarm-engine:9020/api/center;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/devices {
        proxy_pass http://CIS-alarm-engine:9020/api/devices;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/patients {
        proxy_pass http://CIS-alarm-engine:9020/api/patients;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/vitals/ {
        proxy_pass http://CIS-alarm-engine:9020/api/vitals/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/alarm/ {
        proxy_pass http://CIS-alarm-engine:9020/api/alarm/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location /api/alarm-config {
        proxy_pass http://CIS-alarm-engine:9020/api/alarm-config;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }
}
